package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The tool subcommands are wired through main's helpers; these tests cover
// the crypto and manifest logic end to end.

func TestKeygenWritesPrivateKeyAndPrintsPublicKey(t *testing.T) {
	dir := t.TempDir()
	keyFile := filepath.Join(dir, "key.b64")

	// Capture stdout of keygen.
	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	err = keygen([]string{keyFile})
	w.Close()
	os.Stdout = old
	if err != nil {
		t.Fatalf("keygen: %v", err)
	}

	buf := make([]byte, 4096)
	n, _ := r.Read(buf)
	out := strings.TrimSpace(string(buf[:n]))

	pub, err := base64.StdEncoding.DecodeString(out)
	if err != nil || len(pub) != 32 {
		t.Fatalf("keygen printed %q, want base64 32-byte public key", out)
	}

	keyData, err := os.ReadFile(keyFile)
	if err != nil {
		t.Fatal(err)
	}
	priv, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(keyData)))
	if err != nil || len(priv) != ed25519.PrivateKeySize {
		t.Fatalf("private key file invalid: %v", err)
	}
	fi, err := os.Stat(keyFile)
	if err != nil {
		t.Fatal(err)
	}
	if perm := fi.Mode().Perm(); perm != 0o600 {
		t.Errorf("key file mode = %o, want 600", perm)
	}

	// The printed public key must match the private key.
	match := ed25519.PrivateKey(priv).Public().(ed25519.PublicKey)
	if string(match) != string(pub) {
		t.Error("public key does not match private key")
	}

	// Refuse to overwrite an existing key.
	if err := keygen([]string{keyFile}); err == nil {
		t.Error("keygen should refuse to overwrite an existing key file")
	}
}

func TestSignAndVerifyRoundTrip(t *testing.T) {
	dir := t.TempDir()
	payload := filepath.Join(dir, "droidproxy-1.0.0-linux-amd64.tar.gz")
	if err := os.WriteFile(payload, []byte("tarball bytes"), 0o644); err != nil {
		t.Fatal(err)
	}

	_, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	t.Setenv("DROIDPROXY_SIGNING_KEY", base64.StdEncoding.EncodeToString(priv))

	if err := sign([]string{payload}); err != nil {
		t.Fatalf("sign: %v", err)
	}
	sig, err := os.ReadFile(payload + ".sig")
	if err != nil {
		t.Fatal(err)
	}

	// verifySig with the same key must pass — we verify against the key we
	// generated by comparing manually (the embedded placeholder key will not
	// match, which the manifest test covers).
	data, _ := os.ReadFile(payload)
	sigBytes, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(sig)))
	if err != nil {
		t.Fatal(err)
	}
	if !ed25519.Verify(priv.Public().(ed25519.PublicKey), data, sigBytes) {
		t.Error("signature does not verify")
	}

	// Missing env is an error.
	t.Setenv("DROIDPROXY_SIGNING_KEY", "")
	if err := sign([]string{payload}); err == nil {
		t.Error("sign without DROIDPROXY_SIGNING_KEY should fail")
	}
}

func TestManifestWritesFeedAndSums(t *testing.T) {
	dir := t.TempDir()

	// Build signed tarballs for both platforms.
	_, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	for _, plat := range []string{"linux-amd64", "linux-arm64"} {
		name := "droidproxy-1.2.3-" + plat + ".tar.gz"
		payload := []byte("payload " + plat)
		if err := os.WriteFile(filepath.Join(dir, name), payload, 0o644); err != nil {
			t.Fatal(err)
		}
		sig := base64.StdEncoding.EncodeToString(ed25519.Sign(priv, payload))
		if err := os.WriteFile(filepath.Join(dir, name+".sig"), []byte(sig), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// Manifest verifies against the embedded key; point it at the test key.
	oldVerify := verifyFn
	verifyFn = func(data, sig []byte) error {
		sigBytes, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(sig)))
		if err != nil {
			return err
		}
		if !ed25519.Verify(priv.Public().(ed25519.PublicKey), data, sigBytes) {
			return errors.New("bad signature")
		}
		return nil
	}
	t.Cleanup(func() { verifyFn = oldVerify })

	notes := filepath.Join(dir, "notes.md")
	if err := os.WriteFile(notes, []byte("# Notes\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	err = manifest([]string{
		"--version", "1.2.3",
		"--tag", "v1.2.3",
		"--notes-file", notes,
		"--dist", dir,
		"--base-url", "https://example.com/download/",
	})
	if err != nil {
		t.Fatalf("manifest: %v", err)
	}

	feedRaw, err := os.ReadFile(filepath.Join(dir, "latest.json"))
	if err != nil {
		t.Fatal(err)
	}
	var feed struct {
		Version string `json:"version"`
		Tag     string `json:"tag"`
		Notes   string `json:"notes"`
		Assets  map[string]struct {
			URL       string `json:"url"`
			SHA256    string `json:"sha256"`
			Size      int    `json:"size"`
			Signature string `json:"signature"`
		} `json:"assets"`
	}
	if err := parseJSON(feedRaw, &feed); err != nil {
		t.Fatalf("latest.json: %v", err)
	}
	if feed.Version != "1.2.3" || feed.Tag != "v1.2.3" || feed.Notes != "# Notes\n" {
		t.Errorf("unexpected feed: %+v", feed)
	}
	a := feed.Assets["linux-amd64"]
	if a.URL != "https://example.com/download/droidproxy-1.2.3-linux-amd64.tar.gz" || a.Size != len("payload linux-amd64") {
		t.Errorf("unexpected asset: %+v", a)
	}
	if len(a.SHA256) != 64 || a.Signature == "" {
		t.Errorf("asset missing sha256 or signature: %+v", a)
	}

	sums, err := os.ReadFile(filepath.Join(dir, "SHA256SUMS"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(sums), "droidproxy-1.2.3-linux-amd64.tar.gz") {
		t.Errorf("SHA256SUMS missing entry: %s", sums)
	}
}
